{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apigateway.fullname" . -}}
{{- $usersSvcPort := .Values.usersservice.service.port -}}
{{- $authSvcPort := .Values.authservice.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: usersservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /users(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: usersservice-service
              port:
                number: {{$usersSvcPort}} 
{{- end }}